CREATE TABLE IF NOT EXISTS notes (id TEXT PRIMARY KEY, title TEXT, note_type TEXT NOT NULL, folder_id TEXT, content_json TEXT NOT NULL, content_html TEXT NOT NULL, content_text TEXT NOT NULL, content_markdown TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', is_pinned INTEGER NOT NULL DEFAULT 0, is_favorite INTEGER NOT NULL DEFAULT 0, is_archived INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, version INTEGER NOT NULL DEFAULT 1, ai_summary TEXT, ai_tags TEXT, embedding_status TEXT, last_ai_processed_at TEXT);
CREATE TABLE IF NOT EXISTS note_folders (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, icon TEXT NOT NULL, color TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS note_tags (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE COLLATE NOCASE, color TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS note_tag_relations (note_id TEXT NOT NULL, tag_id TEXT NOT NULL, PRIMARY KEY(note_id, tag_id));
CREATE TABLE IF NOT EXISTS note_relations (id TEXT PRIMARY KEY, note_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, relation_type TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS note_attachments (id TEXT PRIMARY KEY, note_id TEXT NOT NULL, file_name TEXT NOT NULL, original_name TEXT NOT NULL, mime_type TEXT NOT NULL, file_size INTEGER NOT NULL, storage_path TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS note_revisions (id TEXT PRIMARY KEY, note_id TEXT NOT NULL, version INTEGER NOT NULL, title TEXT, content_json TEXT NOT NULL, content_html TEXT NOT NULL, content_markdown TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS notes_updated_at_idx ON notes(updated_at);
CREATE INDEX IF NOT EXISTS notes_created_at_idx ON notes(created_at);
CREATE INDEX IF NOT EXISTS notes_deleted_at_idx ON notes(deleted_at);
CREATE INDEX IF NOT EXISTS notes_folder_id_idx ON notes(folder_id);
CREATE INDEX IF NOT EXISTS notes_note_type_idx ON notes(note_type);
CREATE INDEX IF NOT EXISTS notes_favorite_idx ON notes(is_favorite);
CREATE INDEX IF NOT EXISTS notes_pinned_idx ON notes(is_pinned);
CREATE INDEX IF NOT EXISTS note_relations_entity_idx ON note_relations(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS note_tags_note_idx ON note_tag_relations(note_id);
CREATE INDEX IF NOT EXISTS note_tags_tag_idx ON note_tag_relations(tag_id);
CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts USING fts5(title, content_text, summary, content='notes', content_rowid='rowid', tokenize='trigram');
CREATE TRIGGER IF NOT EXISTS notes_fts_insert AFTER INSERT ON notes BEGIN INSERT INTO notes_fts(rowid,title,content_text,summary) VALUES(new.rowid,new.title,new.content_text,new.summary); END;
CREATE TRIGGER IF NOT EXISTS notes_fts_delete AFTER DELETE ON notes BEGIN INSERT INTO notes_fts(notes_fts,rowid,title,content_text,summary) VALUES('delete',old.rowid,old.title,old.content_text,old.summary); END;
CREATE TRIGGER IF NOT EXISTS notes_fts_update AFTER UPDATE ON notes BEGIN INSERT INTO notes_fts(notes_fts,rowid,title,content_text,summary) VALUES('delete',old.rowid,old.title,old.content_text,old.summary); INSERT INTO notes_fts(rowid,title,content_text,summary) VALUES(new.rowid,new.title,new.content_text,new.summary); END;
