// GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by tools/contract-exporter (npm run contracts:generate).
// Rust types in crates/lifetrace-contracts are the authoritative source.

export type AcceptedResponseV1 = { accepted: boolean, };

export type AccountType = string;

export type Activity = { meta: EntityMeta, name: string, activityType: ActivityType, unit: string, minimumTarget: number | null, normalTarget: number | null, targetPeriod: string, targetDays: Array<number>, icon: string | null, color: string | null, scheduleType: ActivityScheduleType | null, startDate: LocalDate | null, checkinMethod: ActivityCheckinMethod | null, syncSource: ActivitySyncSource | null, description: string | null, isArchived: boolean, };

export type ActivityCheckinMethod = string;

export type ActivityLog = { meta: EntityMeta, activityId: EntityId | null, logDate: LocalDate, value: number | null, status: ActivityLogStatus | null, note: string | null, metadata: JsonValue | null, };

export type ActivityLogStatus = string;

export type ActivityScheduleType = string;

export type ActivitySyncSource = string;

export type ActivityType = string;

export type ApiErrorV1 = { code: ErrorCode, message: string, requestId: RequestId | null, retryable: boolean, fieldErrors: Array<FieldError>, details: JsonValue | null, };

export type AppGrantId = string;

export type AppGrantListV1 = { grants: Array<AppGrantV1>, };

export type AppGrantV1 = { id: AppGrantId, appId: AppId, scopes: Array<Scope>, status: string, grantedAt: string, updatedAt: string, revokedAt: string | null, };

export type AppId = string;

export type AppInstallationId = string;

export type ArticleVocabularyItem = { word: string, phonetic: string | null, meaning: string, example: string | null, };

export type AtomicGroupId = string;

export type AuthCapabilitiesV1 = { registrationMode: string, passwordMinLength: number, passwordMaxBytes: number, accessTokenTtlSeconds: bigint, refreshIdleTtlSeconds: bigint, refreshAbsoluteTtlSeconds: bigint, webSessionEnabled: boolean, supportedApps: Array<AppId>, };

export type AuthSessionId = string;

export type AuthSessionV1 = { id: AuthSessionId, appId: AppId, deviceId: AppInstallationId, sessionType: string, status: string, scopes: Array<Scope>, publicDevice: boolean, createdAt: string, lastSeenAt: string, idleExpiresAt: string, absoluteExpiresAt: string, revokedAt: string | null, current: boolean, };

export type AuthUserV1 = { id: UserId, email: string, displayName: string | null, state: string, emailVerifiedAt: string | null, createdAt: string, passwordChangedAt: string | null, };

export type CapabilitiesResponseV1 = { protocolVersion: number, supportedProtocolVersions: Array<number>, schemaVersion: number, minimumSchemaVersion: number, minimumClientVersions: Array<MinimumClientVersion>, maximumPushBatchSize: number, maximumPullBatchSize: number, maximumRequestBytes: bigint, maximumSnapshotPageSize: number, maximumAtomicGroupSize: number, tombstoneRetentionDays: number, supportedEntityTypes: Array<string>, serverTime: string, };

export type ChangeId = string;

export type ChangeOperation = string;

export type ChangePasswordRequestV1 = { currentPassword: string, newPassword: string, };

export type ClientPlatform = string;

export type ConflictId = string;

export type ConflictMode = "optimistic" | "server_authoritative" | "none";

export type ConflictReason = string;

export type ConflictV1 = { conflictId: ConflictId, changeId: ChangeId, entityType: EntityType, entityId: EntityId, clientBaseServerVersion: ServerVersion, currentServerVersion: ServerVersion, 
/**
 * Current server entity (or tombstone payload) for client resolution.
 */
serverEntity: JsonValue | null, serverDeleted: boolean, reason: ConflictReason, };

export type CsrfResponseV1 = { csrfToken: string, };

export type CurrencyCode = string;

export type Cursor = string;

export type DailyReview = { meta: EntityMeta, reviewDate: LocalDate, energy: bigint | null, mood: bigint | null, completionScore: number | null, bestThing: string | null, problem: string | null, tomorrowPriority: string | null, note: string | null, };

export type Device = { meta: EntityMeta, deviceName: string, platform: string, appId: string | null, status: string, lastSeenAt: string | null, };

export type DeviceId = string;

export type DeviceInstallationV1 = { id: AppInstallationId, externalDeviceId: string, deviceGroupId: string | null, deviceName: string, appId: AppId, platform: string, status: string, clientVersion: string | null, firstSeenAt: string, lastSeenAt: string, lastLoginAt: string | null, lastSyncAt: string | null, revokedAt: string | null, current: boolean, };

export type DeviceListV1 = { devices: Array<DeviceInstallationV1>, };

export type EnglishArticle = { meta: EntityMeta, title: string, level: EnglishLevel, category: EnglishCategory, content: string, wordCount: bigint, difficulty: bigint | null, estimatedMinutes: bigint | null, source: string | null, sourceKey: string | null, sourceName: string | null, sourceCategory: string | null, sourceUrl: string | null, normalizedSourceUrl: string | null, externalId: string | null, publishedAt: string | null, sourceUpdatedAt: string | null, imageUrl: string | null, audioUrl: string | null, author: string | null, summary: string | null, fetchedAt: string | null, rightsNote: string | null, contentHash: string | null, language: string | null, qualityScore: number | null, hasAudio: boolean, licenseType: string | null, attribution: string | null, processingStatus: EnglishProcessingStatus | null, fetchStatus: EnglishFetchStatus | null, retryCount: bigint, lastError: string | null, createdTime: string | null, questions: Array<string>, vocabulary: Array<ArticleVocabularyItem>, };

export type EnglishCategory = string;

export type EnglishCompletionStatus = string;

export type EnglishFetchStatus = string;

export type EnglishHighlight = { meta: EntityMeta, articleId: EntityId | null, selectedText: string, blockId: string | null, startOffset: bigint | null, endOffset: bigint | null, color: HighlightColor, prefix: string | null, suffix: string | null, note: string | null, };

export type EnglishLearningRecord = { meta: EntityMeta, articleId: EntityId | null, recordDate: LocalDate, readingTimeSeconds: bigint, summary: string, score: number | null, analysisId: EntityId | null, newWords: Array<string>, completionStatus: EnglishCompletionStatus, readingStatus: EnglishReadingStatus | null, startedAt: string | null, completedAt: string | null, };

export type EnglishLevel = string;

export type EnglishNote = { meta: EntityMeta, articleId: EntityId | null, quote: string | null, content: string, blockId: string | null, startOffset: bigint | null, endOffset: bigint | null, selectedText: string | null, prefix: string | null, suffix: string | null, highlightId: EntityId | null, };

export type EnglishProcessingStatus = string;

export type EnglishReadingStatus = string;

export type EnglishVocabulary = { meta: EntityMeta, normalizedWord: string, displayWord: string, definition: string, phonetic: string, partOfSpeech: string, selectedMeanings: Array<string>, lemma: string, sourceArticleId: EntityId | null, sourceArticleTitle: string | null, sourceSentence: string | null, notes: string, masteryLevel: bigint, reviewStage: bigint, reviewCount: bigint, correctCount: bigint, incorrectCount: bigint, encounterCount: bigint, lastReviewedAt: string | null, nextReviewAt: string | null, status: VocabularyStatus, frequencyRank: bigint | null, tags: Array<string>, metadata: JsonValue | null, };

export type EntityId = string;

export type EntityLink = { meta: EntityMeta, source: EntityRef, target: EntityRef, 
/**
 * Stable, extensible relation type (for example `created_from`,
 * `references`, `attachment`, `summary_of`, `belongs_to`, `evidence_for`).
 */
relationType: string, metadata: JsonValue | null, };

export type EntityMeta = { id: EntityId, userId: UserId, createdAt: string, updatedAt: string, deletedAt: string | null, 
/**
 * Local revision number (never the server-authoritative version).
 */
localVersion: bigint, 
/**
 * Server-authoritative version; `None` until the server first accepts it.
 */
serverVersion: ServerVersion | null, 
/**
 * Device that last modified the entity locally (audit only).
 */
modifiedByDevice: DeviceId | null, };

export type EntityOwnership = "user_owned" | "server_managed" | "shared_catalog" | "device_local" | "secret_local_only";

export type EntityRef = { entityType: EntityType, entityId: EntityId, };

export type EntitySnapshotV1 = { entityType: EntityType, entityId: EntityId, serverVersion: ServerVersion, payload: JsonValue, };

export type EntityType = string;

export type ErrorCode = string;

export type FieldError = { 
/**
 * Field path, for example `changes[3].entityType`.
 */
field: string, 
/**
 * Field-level error code (string; server-defined, forward compatible).
 */
code: string, message: string, };

export type FileMetadata = { meta: EntityMeta, originalName: string, mimeType: string, sizeBytes: bigint, sha256: string, storageState: FileStorageState, createdByDevice: DeviceId | null, };

export type FileStorageState = string;

export type FinanceAccount = { meta: EntityMeta, name: string, accountType: AccountType, 
/**
 * Baseline balance in cents at `balance_at`.
 */
openingBalanceCents: bigint | null, balanceAt: string | null, last4: string | null, color: string, icon: string, isArchived: boolean, currency: CurrencyCode, };

export type ForgotPasswordRequestV1 = { email: string, };

export type HighlightColor = string;

export type ImportStatus = string;

export type JsonValue = unknown;

export type LocalDate = string;

export type LoginRequestV1 = { email: string, password: string, appId: AppId, deviceId: string, deviceName: string, platform: string, clientVersion: string | null, requestedScopes: Array<Scope>, publicDevice: boolean, };

export type MinimumClientVersion = { appId: AppId, clientVersion: string, };

export type MoneyAmount = { 
/**
 * Amount in the smallest currency unit (cents). Never use floats.
 */
amountCents: bigint, currency: CurrencyCode, };

export type Note = { meta: EntityMeta, title: string | null, noteType: NoteType, folderId: EntityId | null, contentJson: JsonValue, contentHtml: string, contentText: string, contentMarkdown: string, summary: string, isPinned: boolean, isFavorite: boolean, isArchived: boolean, aiSummary: string | null, aiTags: string | null, embeddingStatus: string | null, lastAiProcessedAt: string | null, };

export type NoteFolder = { meta: EntityMeta, name: string, icon: string, color: string, sortOrder: bigint, };

export type NoteRelation = { meta: EntityMeta, noteId: EntityId, entityType: EntityType, entityId: EntityId, relationType: string, };

export type NoteRevision = { meta: EntityMeta, noteId: EntityId, 
/**
 * Revision counter within the note (distinct from `meta.localVersion`).
 */
revisionVersion: bigint, title: string | null, contentJson: JsonValue, contentHtml: string, contentMarkdown: string, };

export type NoteTag = { meta: EntityMeta, name: string, color: string, };

export type NoteTagRelation = { meta: EntityMeta, noteId: EntityId, tagId: EntityId, };

export type NoteType = string;

export type PullRequestV1 = { requestId: RequestId, client: SyncClientInfo, 
/**
 * Opaque server cursor. `None` means "start from the beginning" (may be
 * answered with `LIFETRACE_SNAPSHOT_REQUIRED` when history is pruned).
 */
afterCursor: Cursor | null, limit: number, 
/**
 * Optional entity type filter.
 */
entityTypes: Array<EntityType> | null, };

export type PullResponseV1 = { requestId: RequestId, serverTime: string, changes: Array<ServerChangeV1>, nextCursor: Cursor, hasMore: boolean, };

export type PushChangeResultV1 = { "status": "accepted", changeId: ChangeId, entityType: EntityType, entityId: EntityId, serverVersion: ServerVersion, cursor: Cursor, serverModifiedAt: string, } | { "status": "duplicate", changeId: ChangeId, entityType: EntityType, entityId: EntityId, serverVersion: ServerVersion, cursor: Cursor, serverModifiedAt: string, } | { "status": "conflict", conflictId: ConflictId, changeId: ChangeId, entityType: EntityType, entityId: EntityId, clientBaseServerVersion: ServerVersion, currentServerVersion: ServerVersion, serverEntity: JsonValue | null, serverDeleted: boolean, reason: ConflictReason, } | { "status": "rejected", changeId: ChangeId, entityType: EntityType, entityId: EntityId, code: ErrorCode, message: string, fieldErrors: Array<FieldError>, };

export type PushRequestV1 = { 
/**
 * Tracing only; never replaces `changeId` for idempotency.
 */
requestId: RequestId, client: SyncClientInfo, changes: Array<SyncChangeV1>, };

export type PushResponseV1 = { requestId: RequestId, serverTime: string, results: Array<PushChangeResultV1>, latestCursor: Cursor, };

export type RefreshRequestV1 = { refreshToken: string, appId: AppId, deviceId: string, };

export type RegisterRequestV1 = { email: string, password: string, displayName: string | null, inviteToken: string | null, appId: AppId, deviceId: string, deviceName: string, platform: string, clientVersion: string | null, requestedScopes: Array<Scope>, };

export type RequestId = string;

export type ResetPasswordRequestV1 = { token: string, newPassword: string, };

export type Scope = string;

export type ServerChangeV1 = { cursor: Cursor, entityType: EntityType, entityId: EntityId, operation: ChangeOperation, serverVersion: ServerVersion, serverModifiedAt: string, 
/**
 * Present for `upsert`; empty for `delete`.
 */
payload: JsonValue | null, 
/**
 * Present for `delete` (and for conflicts involving deletion).
 */
tombstone: TombstoneV1 | null, originDeviceId: DeviceId | null, };

export type ServerVersion = string;

export type SessionListV1 = { sessions: Array<AuthSessionV1>, };

export type SnapshotId = string;

export type SnapshotRequestV1 = { requestId: RequestId, client: SyncClientInfo, 
/**
 * Omitted on the first page; the server assigns one and expects it on
 * subsequent pages so all pages share one consistent view.
 */
snapshotId: SnapshotId | null, pageToken: string | null, entityTypes: Array<EntityType> | null, pageSize: number, };

export type SnapshotResponseV1 = { requestId: RequestId, snapshotId: SnapshotId, snapshotCursor: Cursor, items: Array<EntitySnapshotV1>, nextPageToken: string | null, completed: boolean, serverTime: string, };

export type SyncChangeV1 = { changeId: ChangeId, entityType: EntityType, entityId: EntityId, operation: ChangeOperation, 
/**
 * Server version the client knew when making this change (`"0"` for new
 * entities). Never fabricated offline.
 */
baseServerVersion: ServerVersion, entitySchemaVersion: number, 
/**
 * Audit only. Never used for global ordering or conflict resolution.
 */
clientModifiedAt: string, 
/**
 * Full entity snapshot for `upsert`; empty for `delete`.
 */
payload: JsonValue | null, 
/**
 * Changes sharing an atomic group must be in one request and succeed or
 * fail together.
 */
atomicGroupId: AtomicGroupId | null, 
/**
 * Entities this change depends on (must exist before applying).
 */
dependencies: Array<EntityRef>, };

export type SyncClientInfo = { appId: AppId, 
/**
 * Client app release version (for example `0.2.1`).
 */
clientVersion: string, platform: ClientPlatform, protocolVersion: number, schemaVersion: number, deviceId: DeviceId, };

export type SyncMode = "bidirectional" | "server_to_client" | "client_to_server" | "not_synced";

export type TokenFamilyId = string;

export type TokenResponseV1 = { accessToken: string, refreshToken: string | null, tokenType: string, expiresIn: bigint, refreshExpiresIn: bigint | null, user: AuthUserV1, session: AuthSessionV1, scopes: Array<Scope>, };

export type TombstoneV1 = { entityType: EntityType, entityId: EntityId, deletedAt: string, serverVersion: ServerVersion, deletedByDevice: DeviceId | null, };

export type TrainingNote = { meta: EntityMeta, title: string, content: string, workoutId: EntityId | null, source: WorkoutSource, noteDate: LocalDate, };

export type Transaction = { meta: EntityMeta, transactionType: TransactionType, 
/**
 * Amount in cents. Never floats on the wire.
 */
amountCents: bigint, currency: CurrencyCode, accountId: EntityId | null, toAccountId: EntityId | null, categoryId: EntityId | null, counterparty: string | null, merchant: string | null, item: string | null, note: string | null, occurredAt: string, 
/**
 * Business natural day `YYYY-MM-DD`; never derived from UTC slicing.
 */
localDate: LocalDate, status: TransactionStatus, sourceType: string, externalTransactionId: string | null, };

export type TransactionCategory = { meta: EntityMeta, name: string, categoryType: TransactionType, parentId: EntityId | null, icon: string | null, color: string | null, isSystem: boolean, isArchived: boolean, };

export type TransactionEvidence = { meta: EntityMeta, transactionId: EntityId, sourceType: string, sourceId: string | null, externalTransactionId: string | null, confidence: number | null, };

export type TransactionStatus = string;

export type TransactionType = string;

export type UpdateAppGrantRequestV1 = { scopes: Array<Scope>, };

export type UpdateDeviceRequestV1 = { deviceName: string, };

export type User = { meta: EntityMeta, displayName: string | null, email: string | null, status: string, };

export type UserId = string;

export type UserPreference = { meta: EntityMeta, preferenceKey: string, value: JsonValue, };

export type VocabularyOccurrence = { meta: EntityMeta, vocabularyId: EntityId, articleId: EntityId | null, articleTitle: string | null, sourceSentence: string, };

export type VocabularyReviewResult = string;

export type VocabularyReviewState = { meta: EntityMeta, vocabularyId: EntityId, dueAt: string | null, difficulty: number | null, stability: number | null, retrievability: number | null, reviewCount: bigint, lapseCount: bigint, schedulerVersion: string | null, };

export type VocabularyStatus = string;

export type WebLoginRequestV1 = { email: string, password: string, requestedScopes: Array<Scope>, publicDevice: boolean, };

export type WebSessionResponseV1 = { user: AuthUserV1, session: AuthSessionV1, csrfToken: string, };

export type Workout = { meta: EntityMeta, source: WorkoutSource, sourceId: string | null, name: string, occurredAt: string, localDate: LocalDate, durationSeconds: bigint, exerciseCount: bigint, setCount: bigint, plannedSetCount: bigint | null, volumeKg: number | null, caloriesKcal: number | null, status: WorkoutStatus | null, };

export type WorkoutExercise = { meta: EntityMeta, workoutId: EntityId, name: string, sortOrder: bigint, plannedSets: bigint, completedSets: bigint, };

export type WorkoutImport = { meta: EntityMeta, source: WorkoutSource, shareUrl: string | null, status: ImportStatus, parser: string | null, parserVersion: string | null, error: string | null, workoutId: EntityId | null, };

export type WorkoutSet = { meta: EntityMeta, exerciseId: EntityId, setNumber: bigint, weightKg: number | null, reps: bigint | null, completed: boolean, };

export type WorkoutSource = string;

export type WorkoutStatus = string;

