import { useMemo, useState } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Save } from "lucide-react";
import { useApp } from "../../app/AppContext";
import { Button, Card, CardContent, Input, MetricCard, PageHeader, Section, Textarea } from "../../components/ui";
import { entities, number, recentDays, text, todayKey } from "../../lib/entities";
import { createDailyReview } from "../../services/core";

export function ReviewPage(){
  const {state,session,upsert}=useApp(); const today=todayKey(); const reviews=entities(state,"review.daily"); const current=reviews.find((item)=>text(item,"reviewDate")===today);
  const [energy,setEnergy]=useState(String(number(current,"energy",3)||3)); const [mood,setMood]=useState(String(number(current,"mood",3)||3)); const [best,setBest]=useState(text(current,"bestThing")); const [problem,setProblem]=useState(text(current,"problem")); const [tomorrow,setTomorrow]=useState(text(current,"tomorrowPriority")); const [note,setNote]=useState(text(current,"note"));
  const days=recentDays(7); const trend=useMemo(()=>days.map((day)=>{const item=reviews.find((r)=>text(r,"reviewDate")===day);return{day:day.slice(5),energy:item?number(item,"energy"):null,mood:item?number(item,"mood"):null}}),[days.join("|"),reviews]);
  async function save(){if(!session)return;const row=createDailyReview(session.user.id,session.session.deviceId,{reviewDate:today,energy:Number(energy),mood:Number(mood),bestThing:best,problem,tomorrowPriority:tomorrow,note},current?.meta.id); if(current) row.meta={...current.meta}; await upsert("review.daily",row);}
  const avgEnergy=reviews.length?reviews.reduce((s,r)=>s+number(r,"energy"),0)/reviews.length:0;
  return <div className="page-shell"><PageHeader title="每日复盘" description="两分钟看清今天，并把下一步留给明天。参考 Shadcnblocks + Tremor。" action={<Button onClick={()=>void save()}><Save size={16}/>保存今天</Button>}/><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="今日能量" value={`${energy}/5`}/><MetricCard label="今日心情" value={`${mood}/5`}/><MetricCard label="历史平均能量" value={avgEnergy?avgEnergy.toFixed(1):"—"}/></div><div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Section title="今天"><Card><CardContent className="grid gap-4 pt-5"><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">能量 1–5<Input type="number" min="1" max="5" className="mt-1.5" value={energy} onChange={(e)=>setEnergy(e.target.value)}/></label><label className="text-sm font-medium">心情 1–5<Input type="number" min="1" max="5" className="mt-1.5" value={mood} onChange={(e)=>setMood(e.target.value)}/></label></div><label className="text-sm font-medium">今天最好的一件事<Input className="mt-1.5" value={best} onChange={(e)=>setBest(e.target.value)}/></label><label className="text-sm font-medium">遇到的问题<Input className="mt-1.5" value={problem} onChange={(e)=>setProblem(e.target.value)}/></label><label className="text-sm font-medium">明天最重要的事<Input className="mt-1.5" value={tomorrow} onChange={(e)=>setTomorrow(e.target.value)}/></label><label className="text-sm font-medium">补充记录<Textarea className="mt-1.5" value={note} onChange={(e)=>setNote(e.target.value)}/></label></CardContent></Card></Section><Section title="7 天状态"><Card><CardContent className="pt-5"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fontSize:11}}/><YAxis domain={[1,5]} width={24} tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey="energy" connectNulls stroke="hsl(var(--chart-1))" strokeWidth={2}/><Line type="monotone" dataKey="mood" connectNulls stroke="hsl(var(--chart-3))" strokeWidth={2}/></LineChart></ResponsiveContainer></div></CardContent></Card></Section></div></div>;
}
