import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Cloud, Download, Plus, RefreshCw, Tags, Upload, WalletCards } from "lucide-react";
import { useApp } from "../../app/AppContext";
import { Badge, Button, Card, CardContent, EmptyState, Input, MetricCard, PageHeader, Progress, Section, cn } from "../../components/ui";
import { entities, number, sum, text, todayKey } from "../../lib/entities";
import {
  createBudgetPreference,
  createFinanceAccount,
  createFinanceCategory,
  createTransaction,
  formatMoney,
  type BeeCountLedger,
  type BeeCountLedgerSnapshot,
  type BeeCountTransaction,
  type JsonEntity,
} from "../../services/core";
import { LifeTraceBeeCountAdapter, beeCountMonthSeries, filterBeeCountTransactions } from "./beecount/adapter";

const PAGE_SIZE = 200;
const tabs = [
  ["overview", "概览"], ["transactions", "交易"], ["calendar", "日历"], ["ledgers", "账本"], ["budgets", "预算"], ["accounts", "账户"], ["categories", "分类"], ["tags", "标签"], ["import", "导入"],
] as const;
type FinanceView = typeof tabs[number][0];

type ImportRow = { date: string; type: "expense" | "income" | "refund" | "fee"; amount: string; merchant: string; note: string };

function currentView(pathname: string): FinanceView {
  const value = pathname.split("/").filter(Boolean).at(-1) ?? "overview";
  return tabs.some(([id]) => id === value) ? value as FinanceView : "overview";
}
function transactionDate(item: JsonEntity) { return text(item,"localDate") || text(item,"occurredAt").slice(0,10); }
function monthOf(date: string) { return date.slice(0,7); }
function nativeBalance(transactions: JsonEntity[]) {
  return transactions.reduce((total,item) => text(item,"transactionType") === "income" ? total + number(item,"amountCents") : ["expense","fee"].includes(text(item,"transactionType")) ? total - number(item,"amountCents") : total,0);
}
function budgetValue(item: JsonEntity): { month: string; amountCents: number; categoryId?: string | null } | null {
  const value = item.value;
  if (!value || typeof value !== "object") return null;
  const row = value as Record<string,unknown>;
  if (typeof row.month !== "string" || typeof row.amountCents !== "number") return null;
  return { month: row.month, amountCents: row.amountCents, categoryId: typeof row.categoryId === "string" ? row.categoryId : null };
}

export function FinanceWorkspace() {
  const { state, session, upsert, privacy, online } = useApp();
  const navigate = useNavigate();
  const location = useLocation();
  const view = currentView(location.pathname);
  const adapter = useMemo(() => new LifeTraceBeeCountAdapter(), []);
  const nativeAccounts = entities(state,"finance.account");
  const nativeCategories = entities(state,"finance.category");
  const nativeTransactions = entities(state,"finance.transaction").filter((item)=>text(item,"status","confirmed") === "confirmed").sort((a,b)=>text(b,"occurredAt").localeCompare(text(a,"occurredAt")));
  const budgetPreferences = entities(state,"user.preference").filter((item)=>text(item,"preferenceKey").startsWith("finance.budget."));
  const [ledgers,setLedgers] = useState<BeeCountLedger[]>([]);
  const [selectedLedgerId,setSelectedLedgerId] = useState("");
  const [snapshot,setSnapshot] = useState<BeeCountLedgerSnapshot|null>(null);
  const [beeCountEnabled,setBeeCountEnabled] = useState<boolean|null>(null);
  const [beeCountReachable,setBeeCountReachable] = useState(false);
  const [loading,setLoading] = useState(false);
  const [error,setError] = useState("");
  const [source,setSource] = useState<"beecount"|"lifetrace">("beecount");

  async function loadBeeCount(preferredId = selectedLedgerId) {
    if (!online) return;
    setLoading(true); setError("");
    try {
      const status = await adapter.status();
      setBeeCountEnabled(status.enabled); setBeeCountReachable(status.upstreamReachable);
      if (!status.enabled || !status.upstreamReachable) { setLedgers([]); setSnapshot(null); setSource("lifetrace"); return; }
      const response = await adapter.ledgers();
      setLedgers(response.items);
      const ledgerId = response.items.some((item)=>item.sourceId===preferredId) ? preferredId : response.items[0]?.sourceId ?? "";
      setSelectedLedgerId(ledgerId);
      if (ledgerId) setSnapshot(await adapter.snapshot(ledgerId,PAGE_SIZE,0));
    } catch (cause) { setError(cause instanceof Error ? cause.message : "BeeCount Cloud 加载失败"); setSource("lifetrace"); }
    finally { setLoading(false); }
  }
  useEffect(()=>{ void loadBeeCount(); },[online]);
  async function chooseLedger(id:string){setSelectedLedgerId(id);setLoading(true);setError("");try{setSnapshot(await adapter.snapshot(id,PAGE_SIZE,0));}catch(cause){setError(cause instanceof Error?cause.message:"账本加载失败");}finally{setLoading(false);}}

  const currency = snapshot?.ledger.currency ?? "CNY";
  const nativeMonth = todayKey().slice(0,7);
  const nativeMonthTx = nativeTransactions.filter((item)=>monthOf(transactionDate(item))===nativeMonth);
  const nativeIncome = sum(nativeMonthTx.filter((item)=>text(item,"transactionType")==="income").map((item)=>number(item,"amountCents")));
  const nativeExpense = sum(nativeMonthTx.filter((item)=>["expense","fee"].includes(text(item,"transactionType"))).map((item)=>number(item,"amountCents")));
  const nativeSeries = useMemo(()=>{
    const buckets=new Map<string,{month:string;income:number;expense:number}>();
    nativeTransactions.forEach((item)=>{const month=monthOf(transactionDate(item));const row=buckets.get(month)??{month,income:0,expense:0};if(text(item,"transactionType")==="income")row.income+=number(item,"amountCents");else if(["expense","fee"].includes(text(item,"transactionType")))row.expense+=number(item,"amountCents");buckets.set(month,row)});return [...buckets.values()].sort((a,b)=>a.month.localeCompare(b.month)).slice(-12);
  },[nativeTransactions]);

  return <div className="page-shell">
    <PageHeader title="财务" description="信息架构与核心视图来自 BeeCount Cloud Web；LifeTrace AppShell 只替换全局导航、账号与主题层。" action={<div className="flex gap-2"><Button variant="outline" onClick={()=>void loadBeeCount()} disabled={loading||!online}><RefreshCw size={15} className={loading?"animate-spin":""}/>刷新</Button>{view==="transactions"?<Button onClick={()=>navigate("/app/finance/transactions?new=1")}><Plus size={15}/>记一笔</Button>:null}</div>} />

    <div className="mb-4 flex flex-col gap-3 rounded-lg border bg-card p-3 lg:flex-row lg:items-center lg:justify-between">
      <div className="flex flex-wrap items-center gap-2"><span className="flex items-center gap-2 text-sm font-semibold"><Cloud size={16}/>数据源</span><div className="flex rounded-md border p-0.5"><button className={cn("rounded px-3 py-1.5 text-xs",source==="beecount"&&"bg-muted font-medium")} disabled={!beeCountEnabled||!beeCountReachable} onClick={()=>setSource("beecount")}>BeeCount Cloud</button><button className={cn("rounded px-3 py-1.5 text-xs",source==="lifetrace"&&"bg-muted font-medium")} onClick={()=>setSource("lifetrace")}>LifeTrace Native</button></div>{beeCountEnabled===false?<Badge>适配器未启用</Badge>:beeCountEnabled&& !beeCountReachable?<Badge className="text-warning">上游不可达</Badge>:beeCountEnabled?<Badge className="text-success">BeeCount 已连接</Badge>:null}</div>
      {source==="beecount"?<label className="flex items-center gap-2 text-xs text-muted-foreground">当前账本<select className="h-9 max-w-56 rounded-md border bg-background px-2 text-sm text-foreground" value={selectedLedgerId} onChange={(e)=>void chooseLedger(e.target.value)}>{ledgers.map((ledger)=><option key={ledger.id} value={ledger.sourceId}>{ledger.name} · {ledger.currency}</option>)}</select></label>:<div className="text-xs text-muted-foreground">当前账号 · {nativeTransactions.length} 笔 native 交易</div>}
    </div>

    {error?<div className="mb-4 rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>:null}
    <nav className="scrollbar-thin mb-5 flex gap-1 overflow-x-auto border-b pb-2" aria-label="财务导航">{tabs.map(([id,label])=><button key={id} onClick={()=>navigate(id==="overview"?"/app/finance":`/app/finance/${id}`)} className={cn("shrink-0 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-muted",view===id&&"bg-accent font-medium text-accent-foreground")}>{label}</button>)}</nav>

    {view==="overview"?<FinanceOverview source={source} snapshot={snapshot} nativeTransactions={nativeTransactions} nativeIncome={nativeIncome} nativeExpense={nativeExpense} nativeSeries={nativeSeries} privacy={privacy}/>:null}
    {view==="transactions"?<TransactionsView source={source} snapshot={snapshot} nativeTransactions={nativeTransactions} accounts={nativeAccounts} categories={nativeCategories} session={session} upsert={upsert} privacy={privacy}/>:null}
    {view==="calendar"?<FinanceCalendar source={source} snapshot={snapshot} nativeTransactions={nativeTransactions}/>:null}
    {view==="ledgers"?<LedgersView source={source} ledgers={ledgers} snapshot={snapshot} nativeTransactions={nativeTransactions} privacy={privacy}/>:null}
    {view==="budgets"?<BudgetsView source={source} snapshot={snapshot} preferences={budgetPreferences} transactions={nativeTransactions} categories={nativeCategories} session={session} upsert={upsert} privacy={privacy}/>:null}
    {view==="accounts"?<AccountsView source={source} snapshot={snapshot} nativeAccounts={nativeAccounts} session={session} upsert={upsert} privacy={privacy}/>:null}
    {view==="categories"?<CategoriesView source={source} snapshot={snapshot} nativeCategories={nativeCategories} session={session} upsert={upsert}/>:null}
    {view==="tags"?<TagsView source={source} snapshot={snapshot}/>:null}
    {view==="import"?<ImportView accounts={nativeAccounts} categories={nativeCategories} session={session} upsert={upsert}/>:null}
  </div>;
}

function FinanceOverview({source,snapshot,nativeTransactions,nativeIncome,nativeExpense,nativeSeries,privacy}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;nativeTransactions:JsonEntity[];nativeIncome:number;nativeExpense:number;nativeSeries:Array<{month:string;income:number;expense:number}>;privacy:boolean}){
  const beecountSeries=snapshot?beeCountMonthSeries(snapshot):[]; const series=source==="beecount"?beecountSeries:nativeSeries;
  const metrics=source==="beecount"&&snapshot?{balance:snapshot.ledger.balanceCents,income:snapshot.ledger.incomeTotalCents,expense:snapshot.ledger.expenseTotalCents,count:snapshot.ledger.transactionCount,currency:snapshot.ledger.currency}:{balance:nativeBalance(nativeTransactions),income:nativeIncome,expense:nativeExpense,count:nativeTransactions.length,currency:"CNY"};
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="余额" value={formatMoney(metrics.balance,metrics.currency,privacy)} hint={`${metrics.count} 笔交易`}/><MetricCard label="收入" value={formatMoney(metrics.income,metrics.currency,privacy)} hint={source==="beecount"?"BeeCount 汇总":"本月"}/><MetricCard label="支出" value={formatMoney(metrics.expense,metrics.currency,privacy)} hint={source==="beecount"?"BeeCount 汇总":"本月"}/><MetricCard label="结余率" value={metrics.income?`${Math.round((metrics.income-metrics.expense)/metrics.income*100)}%`:"—"} hint="收入 - 支出"/></div><div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><Section title="收支趋势" description="Upstream: OverviewPage multi-scope analytics → LifeTrace snapshot/native adapter"><Card><CardContent className="pt-5"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={series}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{fontSize:10}}/><YAxis hide/><Tooltip/><Bar dataKey="expense" fill="hsl(var(--expense))" radius={[3,3,0,0]}/><Bar dataKey="income" fill="hsl(var(--income))" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card></Section><Section title="账户与预算"><Card><CardContent className="space-y-4 pt-5">{source==="beecount"&&snapshot?<><div className="flex justify-between text-sm"><span className="text-muted-foreground">账户</span><strong>{snapshot.accounts.length}</strong></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">预算</span><strong>{snapshot.budgets.length}</strong></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">分类 / 标签</span><strong>{snapshot.categories.length} / {snapshot.tags.length}</strong></div><div className="rounded-md bg-muted/50 p-3 text-xs leading-5 text-muted-foreground">{snapshot.ledger.isShared?`${snapshot.ledger.memberCount??1} 人共享账本`:"个人账本"} · 权限 {snapshot.ledger.role??"viewer"}</div></>:<div className="text-sm text-muted-foreground">LifeTrace Native 使用统一 Cloud entity 同步。切换到对应页维护账户、分类和预算。</div>}</CardContent></Card></Section></div></>;
}

function TransactionsView({source,snapshot,nativeTransactions,accounts,categories,session,upsert,privacy}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;nativeTransactions:JsonEntity[];accounts:JsonEntity[];categories:JsonEntity[];session:ReturnType<typeof useApp>["session"];upsert:ReturnType<typeof useApp>["upsert"];privacy:boolean}){
  const [query,setQuery]=useState("");const [type,setType]=useState("all");const [showNew,setShowNew]=useState(false);const [amount,setAmount]=useState("");const [merchant,setMerchant]=useState("");const [accountId,setAccountId]=useState("");const [categoryId,setCategoryId]=useState("");const [txType,setTxType]=useState<"expense"|"income">("expense");
  const beeItems=useMemo(()=>filterBeeCountTransactions(snapshot?.transactions.items??[],query,type),[snapshot?.transactions.items,query,type]);
  const nativeItems=useMemo(()=>nativeTransactions.filter((item)=>(type==="all"||text(item,"transactionType")===type)&&`${text(item,"merchant")} ${text(item,"note")} ${transactionDate(item)}`.toLowerCase().includes(query.toLowerCase())),[nativeTransactions,query,type]);
  async function create(event:FormEvent){event.preventDefault();if(!session)return;await upsert("finance.transaction",createTransaction(session.user.id,session.session.deviceId,{amount,type:txType,merchant,accountId:accountId||null,categoryId:categoryId||null}));setAmount("");setMerchant("");setShowNew(false);}
  const beeMap=(item:BeeCountTransaction)=>({id:item.id,title:item.note||item.categoryName||item.accountName||"交易",date:item.localDate||item.occurredAt.slice(0,10),type:item.transactionType,amount:item.amountCents,currency:item.currency,meta:[item.accountName,item.categoryName,...item.tags].filter(Boolean).join(" · ")});
  const rows=source==="beecount"?beeItems.map(beeMap):nativeItems.map((item)=>({id:item.meta.id,title:text(item,"merchant",text(item,"item",text(item,"note","交易"))),date:transactionDate(item),type:text(item,"transactionType"),amount:number(item,"amountCents"),currency:text(item,"currency","CNY"),meta:[text(accounts.find((a)=>a.meta.id===item.accountId),"name"),text(categories.find((c)=>c.meta.id===item.categoryId),"name")].filter(Boolean).join(" · ")}));
  return <><div className="mb-4 flex flex-col gap-2 sm:flex-row"><Input placeholder="筛选备注、账户、分类或日期" value={query} onChange={(e)=>setQuery(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={type} onChange={(e)=>setType(e.target.value)}><option value="all">全部类型</option><option value="expense">支出</option><option value="income">收入</option><option value="refund">退款</option><option value="fee">手续费</option></select>{source==="lifetrace"?<Button onClick={()=>setShowNew(true)}><Plus size={15}/>记一笔</Button>:<Badge className="h-10 px-3">BeeCount 当前适配器只读</Badge>}</div>{showNew?<Card className="mb-4"><CardContent className="pt-5"><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-6" onSubmit={(e)=>void create(e)}><select className="h-10 rounded-md border bg-background px-3 text-sm" value={txType} onChange={(e)=>setTxType(e.target.value as "expense"|"income")}><option value="expense">支出</option><option value="income">收入</option></select><Input type="number" step="0.01" min="0.01" required value={amount} onChange={(e)=>setAmount(e.target.value)} placeholder="金额"/><Input value={merchant} onChange={(e)=>setMerchant(e.target.value)} placeholder="商户/说明"/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={accountId} onChange={(e)=>setAccountId(e.target.value)}><option value="">默认账户</option>{accounts.map((item)=><option key={item.meta.id} value={item.meta.id}>{text(item,"name")}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={categoryId} onChange={(e)=>setCategoryId(e.target.value)}><option value="">未分类</option>{categories.filter((item)=>text(item,"categoryType")===txType).map((item)=><option key={item.meta.id} value={item.meta.id}>{text(item,"name")}</option>)}</select><div className="flex gap-2"><Button type="submit">保存</Button><Button variant="ghost" onClick={()=>setShowNew(false)}>取消</Button></div></form></CardContent></Card>:null}<Card>{rows.length?<div className="divide-y">{rows.map((row)=><div key={row.id} className="flex items-center gap-3 px-4 py-3"><div className={cn("flex h-8 w-8 items-center justify-center rounded-md text-xs font-semibold",row.type==="income"?"bg-success/10 text-success":"bg-destructive/10 text-destructive")}>{row.type==="income"?"收":"支"}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{row.title}</div><div className="mt-0.5 truncate text-xs text-muted-foreground">{row.date}{row.meta?` · ${row.meta}`:""}</div></div><strong className={cn("text-sm tabular-nums",row.type==="income"?"text-income":"text-expense")}>{row.type==="income"?"+":"-"}{formatMoney(row.amount,row.currency,privacy)}</strong></div>)}</div>:<CardContent className="pt-5"><EmptyState title="没有匹配的交易" description="调整筛选条件或新增一笔记录。"/></CardContent>}</Card></>;
}

function FinanceCalendar({source,snapshot,nativeTransactions}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;nativeTransactions:JsonEntity[]}){const values=source==="beecount"?(snapshot?.transactions.items??[]).map((item)=>({date:item.localDate||item.occurredAt.slice(0,10),amount:item.amountCents,type:item.transactionType})) : nativeTransactions.map((item)=>({date:transactionDate(item),amount:number(item,"amountCents"),type:text(item,"transactionType")}));const byDate=new Map<string,{income:number;expense:number;count:number}>();values.forEach((item)=>{const row=byDate.get(item.date)??{income:0,expense:0,count:0};row.count++;if(item.type==="income")row.income+=item.amount;else if(["expense","fee"].includes(item.type))row.expense+=item.amount;byDate.set(item.date,row)});return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[...byDate.entries()].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,60).map(([date,row])=><Card key={date}><CardContent className="pt-5"><div className="flex items-center justify-between"><strong>{date}</strong><Badge>{row.count} 笔</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><div className="text-xs text-muted-foreground">收入</div><div className="mt-1 font-semibold text-income">{formatMoney(row.income,"CNY")}</div></div><div><div className="text-xs text-muted-foreground">支出</div><div className="mt-1 font-semibold text-expense">{formatMoney(row.expense,"CNY")}</div></div></div></CardContent></Card>)}{!byDate.size?<EmptyState title="暂无日历数据" description="交易发生后按日期聚合展示。"/>:null}</div>}

function LedgersView({source,ledgers,snapshot,nativeTransactions,privacy}:{source:"beecount"|"lifetrace";ledgers:BeeCountLedger[];snapshot:BeeCountLedgerSnapshot|null;nativeTransactions:JsonEntity[];privacy:boolean}){if(source==="lifetrace")return <Card><CardContent className="pt-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-md bg-muted"><WalletCards size={18}/></div><div><div className="font-semibold">LifeTrace Native</div><div className="text-xs text-muted-foreground">当前 LifeTrace Cloud 账号</div></div></div><div className="mt-5 text-2xl font-semibold">{formatMoney(nativeBalance(nativeTransactions),"CNY",privacy)}</div><div className="mt-1 text-xs text-muted-foreground">{nativeTransactions.length} 笔交易</div></CardContent></Card>;return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{ledgers.map((ledger)=><Card key={ledger.id} className={snapshot?.ledger.sourceId===ledger.sourceId?"border-primary":""}><CardContent className="pt-5"><div className="flex items-center justify-between"><div className="font-semibold">{ledger.name}</div><Badge>{ledger.isShared?"共享":"个人"}</Badge></div><div className="mt-4 text-xl font-semibold">{formatMoney(ledger.balanceCents,ledger.currency,privacy)}</div><div className="mt-2 text-xs text-muted-foreground">{ledger.transactionCount} 笔 · {ledger.currency} · {ledger.role??"viewer"}</div></CardContent></Card>)}</div>}

function BudgetsView({source,snapshot,preferences,transactions,categories,session,upsert,privacy}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;preferences:JsonEntity[];transactions:JsonEntity[];categories:JsonEntity[];session:ReturnType<typeof useApp>["session"];upsert:ReturnType<typeof useApp>["upsert"];privacy:boolean}){const [amount,setAmount]=useState("");const month=todayKey().slice(0,7);async function add(e:FormEvent){e.preventDefault();if(!session)return;await upsert("user.preference",createBudgetPreference(session.user.id,session.session.deviceId,month,amount));setAmount("");}if(source==="beecount")return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{snapshot?.budgets.length?snapshot.budgets.map((budget)=><Card key={budget.id}><CardContent className="pt-5"><div className="flex justify-between"><strong>{budget.categoryName||"总预算"}</strong><Badge>{budget.period}</Badge></div><div className="mt-4 text-xl font-semibold">{formatMoney(budget.amountCents,snapshot.ledger.currency,privacy)}</div><div className="mt-2 text-xs text-muted-foreground">每期第 {budget.startDay} 日开始 · {budget.enabled?"启用":"停用"}</div></CardContent></Card>):<EmptyState title="BeeCount 暂无预算" description="当前适配器按上游快照只读展示。"/>}</div>;const rows=preferences.map((item)=>({item,value:budgetValue(item)})).filter((row):row is {item:JsonEntity;value:NonNullable<ReturnType<typeof budgetValue>>}=>Boolean(row.value));return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="grid gap-4 md:grid-cols-2">{rows.map(({item,value})=>{const spent=sum(transactions.filter((tx)=>transactionDate(tx).startsWith(value.month)&&(!value.categoryId||tx.categoryId===value.categoryId)&&["expense","fee"].includes(text(tx,"transactionType"))).map((tx)=>number(tx,"amountCents")));const pct=value.amountCents?Math.round(spent/value.amountCents*100):0;return <Card key={item.meta.id}><CardContent className="pt-5"><div className="flex justify-between"><strong>{value.categoryId?text(categories.find((c)=>c.meta.id===value.categoryId),"name","分类预算"):"总预算"}</strong><Badge>{value.month}</Badge></div><div className="mt-4 flex justify-between text-sm"><span>{formatMoney(spent,"CNY",privacy)}</span><span className="text-muted-foreground">/ {formatMoney(value.amountCents,"CNY",privacy)}</span></div><Progress className="mt-2" value={pct}/></CardContent></Card>)}{!rows.length?<EmptyState title="暂无预算" description="创建预算后会跟随交易自动计算使用率。"/>:null}</div><Card className="h-fit"><CardContent className="pt-5"><div className="font-semibold">创建本月总预算</div><form className="mt-4 space-y-3" onSubmit={(e)=>void add(e)}><Input type="number" min="0.01" step="0.01" value={amount} onChange={(e)=>setAmount(e.target.value)} placeholder="预算金额" required/><Button type="submit" className="w-full">保存预算</Button></form></CardContent></Card></div>}

function AccountsView({source,snapshot,nativeAccounts,session,upsert,privacy}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;nativeAccounts:JsonEntity[];session:ReturnType<typeof useApp>["session"];upsert:ReturnType<typeof useApp>["upsert"];privacy:boolean}){const [name,setName]=useState("");async function add(e:FormEvent){e.preventDefault();if(!session)return;await upsert("finance.account",createFinanceAccount(session.user.id,session.session.deviceId,name));setName("");}const rows=source==="beecount"?(snapshot?.accounts??[]).map((item)=>({id:item.id,name:item.name,type:item.accountType||"账户",balance:item.balanceCents??item.openingBalanceCents??0,currency:item.currency||snapshot?.ledger.currency||"CNY"})) : nativeAccounts.map((item)=>({id:item.meta.id,name:text(item,"name","账户"),type:text(item,"accountType","账户"),balance:number(item,"openingBalanceCents"),currency:text(item,"currency","CNY")}));return <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((item)=><Card key={item.id}><CardContent className="pt-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><WalletCards size={17}/><strong>{item.name}</strong></div><Badge>{item.type}</Badge></div><div className="mt-4 text-xl font-semibold">{formatMoney(item.balance,item.currency,privacy)}</div></CardContent></Card>)}</div>{source==="lifetrace"?<Card className="mt-5"><CardContent className="pt-5"><form className="flex gap-2" onSubmit={(e)=>void add(e)}><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder="新账户名称" required/><Button type="submit"><Plus size={15}/>新建账户</Button></form></CardContent></Card>:null}</>}

function CategoriesView({source,snapshot,nativeCategories,session,upsert}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null;nativeCategories:JsonEntity[];session:ReturnType<typeof useApp>["session"];upsert:ReturnType<typeof useApp>["upsert"]}){const [name,setName]=useState("");const [kind,setKind]=useState<"expense"|"income">("expense");async function add(e:FormEvent){e.preventDefault();if(!session)return;await upsert("finance.category",createFinanceCategory(session.user.id,session.session.deviceId,name,kind));setName("");}const rows=source==="beecount"?(snapshot?.categories??[]).map((item)=>({id:item.id,name:item.name,kind:item.categoryType,parent:item.parentName,count:item.transactionCount??0})) : nativeCategories.map((item)=>({id:item.meta.id,name:text(item,"name"),kind:text(item,"categoryType"),parent:"",count:0}));return <><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{rows.map((item)=><Card key={item.id}><CardContent className="pt-5"><div className="flex justify-between"><strong>{item.name}</strong><Badge>{item.kind==="income"?"收入":"支出"}</Badge></div><div className="mt-2 text-xs text-muted-foreground">{item.parent?`上级：${item.parent}`:`${item.count} 笔交易`}</div></CardContent></Card>)}</div>{source==="lifetrace"?<Card className="mt-5"><CardContent className="pt-5"><form className="grid gap-2 sm:grid-cols-[1fr_150px_auto]" onSubmit={(e)=>void add(e)}><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder="分类名称" required/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={kind} onChange={(e)=>setKind(e.target.value as "expense"|"income")}><option value="expense">支出</option><option value="income">收入</option></select><Button type="submit">新建分类</Button></form></CardContent></Card>:null}</>}

function TagsView({source,snapshot}:{source:"beecount"|"lifetrace";snapshot:BeeCountLedgerSnapshot|null}){if(source==="lifetrace")return <EmptyState icon={<Tags size={24}/>} title="LifeTrace Native 当前没有财务标签实体" description="标签视图保留 BeeCount 上游信息架构；native schema 扩展标签前不伪造数据。"/>;return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{snapshot?.tags.length?snapshot.tags.map((tag)=><Card key={tag.id}><CardContent className="pt-5"><div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full border" style={{background:tag.color||undefined}}/><strong>{tag.name}</strong></div><div className="mt-3 text-xs text-muted-foreground">{tag.transactionCount??0} 笔交易</div></CardContent></Card>):<EmptyState title="暂无标签" description="BeeCount 当前账本没有标签。"/>}</div>}

function ImportView({accounts,categories,session,upsert}:{accounts:JsonEntity[];categories:JsonEntity[];session:ReturnType<typeof useApp>["session"];upsert:ReturnType<typeof useApp>["upsert"]}){const [rows,setRows]=useState<ImportRow[]>([]);const [message,setMessage]=useState("");async function selectFile(file:File){const raw=await file.text();const lines=raw.split(/\r?\n/).filter(Boolean);if(lines.length<2){setMessage("CSV 没有数据行");return;}const header=lines[0].split(",").map((v)=>v.trim().toLowerCase());const index=(name:string)=>header.indexOf(name);const parsed=lines.slice(1).map((line)=>{const c=line.split(",").map((v)=>v.trim().replace(/^"|"$/g,""));const rawType=c[index("type")]||"expense";return{date:c[index("date")]||todayKey(),type:(["expense","income","refund","fee"].includes(rawType)?rawType:"expense") as ImportRow["type"],amount:c[index("amount")]||"0",merchant:c[index("merchant")]||"",note:c[index("note")]||""}}).filter((row)=>Number(row.amount)>0);setRows(parsed);setMessage(`${parsed.length} 行可导入`);}async function commit(){if(!session)return;setMessage("正在写入…");try{for(const row of rows){await upsert("finance.transaction",createTransaction(session.user.id,session.session.deviceId,{type:row.type,amount:row.amount,localDate:row.date,occurredAt:new Date(`${row.date}T12:00:00`).toISOString(),merchant:row.merchant,note:row.note,accountId:accounts[0]?.meta.id??null,categoryId:categories.find((item)=>text(item,"categoryType")===row.type)?.meta.id??null,sourceType:"web_csv_import"}));}setMessage(`已导入 ${rows.length} 笔`);setRows([]);}catch(cause){setMessage(cause instanceof Error?cause.message:"导入失败");}}return <div className="grid gap-5 lg:grid-cols-[360px_minmax(0,1fr)]"><Card className="h-fit"><CardContent className="pt-5"><div className="flex items-center gap-2 font-semibold"><Upload size={17}/>CSV 导入</div><p className="mt-2 text-xs leading-5 text-muted-foreground">支持表头：date,type,amount,merchant,note。文件只在内存解析，确认后逐笔写入 LifeTrace Cloud。</p><label className="mt-4 flex cursor-pointer items-center justify-center rounded-md border border-dashed p-6 text-sm hover:bg-muted"><input type="file" accept=".csv,text/csv" className="hidden" onChange={(e)=>{const file=e.target.files?.[0];if(file)void selectFile(file)}}/><Download size={16} className="mr-2"/>选择 CSV</label>{message?<div className="mt-3 text-xs text-muted-foreground">{message}</div>:null}{rows.length?<Button className="mt-4 w-full" onClick={()=>void commit()}>确认导入 {rows.length} 笔</Button>:null}</CardContent></Card><Card><div className="divide-y">{rows.length?rows.slice(0,100).map((row,index)=><div key={`${row.date}-${index}`} className="grid grid-cols-[90px_70px_90px_1fr] gap-2 px-4 py-2.5 text-xs"><span>{row.date}</span><span>{row.type}</span><span>{row.amount}</span><span className="truncate">{row.merchant||row.note||"—"}</span></div>):<CardContent className="pt-5"><EmptyState title="等待选择文件" description="导入前会先显示预览，不会把原始文件上传或持久化到浏览器。"/></CardContent>}</div></Card></div>}
