"use client";

import { useEffect, useState } from "react";
import { Archive, BarChart3, BookOpen, CalendarDays, Check, ChevronRight, CircleDollarSign, Cloud, CloudOff, Download, Dumbbell, Home, Menu, Moon, Music2, Pause, Pencil, Play, Plus, Settings, Shield, Square, Sun, Timer, UserRound, WalletCards, X } from "lucide-react";
import { useLifeStore } from "@/src/stores/useLifeStore";
import type { Activity, ActivityLog, ViewId } from "@/src/types";

const nav: { id: ViewId; label: string; icon: typeof Home }[] = [
  { id: "today", label: "今日", icon: Home }, { id: "calendar", label: "日历", icon: CalendarDays },
  { id: "activities", label: "项目", icon: BookOpen }, { id: "finance", label: "记账", icon: WalletCards },
  { id: "statistics", label: "统计", icon: BarChart3 }, { id: "review", label: "复盘", icon: Check }, { id: "settings", label: "设置", icon: Settings },
];

const activityIcon = (name?: string) => name === "music" ? Music2 : name === "fitness" ? Dumbbell : name === "shield" ? Shield : BookOpen;

function QuickSheet({ onClose }: { onClose: () => void }) {
  const { activities, addLog, addTransaction, setView, startTimer } = useLifeStore();
  const [mode, setMode] = useState<"menu" | "log" | "timer" | "finance" | "control">("menu");
  const [activityId, setActivityId] = useState(activities.find((item) => item.type === "duration")?.id ?? activities[0]?.id ?? "");
  const [value, setValue] = useState("30");
  const [amount, setAmount] = useState("");
  const [category, setCategory] = useState("餐饮");
  const [transactionType, setTransactionType] = useState<"expense" | "income">("expense");
  const [account, setAccount] = useState("微信");
  const finish = () => { onClose(); };
  if (mode === "menu") return <div className="sheet-panel"><div className="sheet-head"><div><span className="eyebrow">快速记录</span><h2>此刻，记下什么？</h2></div><button className="icon-button" onClick={onClose} aria-label="关闭"><X /></button></div><div className="quick-grid">
    <button onClick={() => setMode("log")}><Timer /><span><b>记录项目</b><small>时长、次数或完成状态</small></span><ChevronRight /></button>
    <button onClick={() => setMode("timer")}><Play /><span><b>开始计时</b><small>刷新页面也不会丢失进度</small></span><ChevronRight /></button>
    <button onClick={() => setMode("finance")}><CircleDollarSign /><span><b>记一笔</b><small>快速记录收入或支出</small></span><ChevronRight /></button>
    <button onClick={() => setMode("control")}><Shield /><span><b>记录状态</b><small>平稳、冲动或失控</small></span><ChevronRight /></button>
    <button onClick={() => { setView("review"); finish(); }}><Check /><span><b>每日复盘</b><small>用两分钟收好今天</small></span><ChevronRight /></button>
  </div></div>;
  if (mode === "timer") return <form className="sheet-panel form-stack" onSubmit={(e) => { e.preventDefault(); startTimer(activityId); finish(); }}><div className="sheet-head"><div><span className="eyebrow">专注计时</span><h2>选择一个项目</h2></div><button className="icon-button" type="button" onClick={onClose}><X /></button></div><label>项目<select value={activityId} onChange={(e) => setActivityId(e.target.value)}>{activities.filter(a => a.type === "duration").map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><p className="form-hint">计时状态会保存在当前设备，关闭或刷新页面后仍可继续。</p><button className="primary-button" type="submit"><Play/> 开始计时</button></form>;
  if (mode === "finance") { const categories = transactionType === "expense" ? ["餐饮","交通","购物","娱乐","居住","医疗","学习","其他"] : ["工资","奖金","兼职","退款","其他"]; return <form className="sheet-panel form-stack" onSubmit={async (e) => { e.preventDefault(); await addTransaction({ type: transactionType, amount: Number(amount), category, account }); finish(); }}><div className="sheet-head"><div><span className="eyebrow">快速记账</span><h2>记录一笔{transactionType === "expense" ? "支出" : "收入"}</h2></div><button className="icon-button" type="button" onClick={onClose}><X /></button></div><div className="segmented wide"><button type="button" className={transactionType === "expense" ? "active" : ""} onClick={() => { setTransactionType("expense"); setCategory("餐饮"); }}>支出</button><button type="button" className={transactionType === "income" ? "active" : ""} onClick={() => { setTransactionType("income"); setCategory("工资"); }}>收入</button></div><label>金额<div className="money-input"><span>¥</span><input autoFocus required min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="0.00" /></div></label><label>分类<select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map(x => <option key={x}>{x}</option>)}</select></label><label>账户<select value={account} onChange={(e) => setAccount(e.target.value)}>{["微信","支付宝","银行卡","现金"].map(x => <option key={x}>{x}</option>)}</select></label><button className="primary-button" type="submit">保存{transactionType === "expense" ? "支出" : "收入"}</button></form>; }
  if (mode === "control") return <div className="sheet-panel form-stack"><div className="sheet-head"><div><span className="eyebrow">状态记录</span><h2>现在感觉如何？</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><div className="state-options">{[["stable","平稳","状态不错，继续保持"],["urge","有冲动","有感觉，但仍在掌控"],["relapse","已失控","如实记录，重新开始"]].map(([state,title,desc]) => <button key={state} onClick={async () => { await addLog("control", undefined, "completed", { state: state as "stable"|"urge"|"relapse" }); finish(); }}><span className={`state-dot ${state}`} /><span><b>{title}</b><small>{desc}</small></span></button>)}</div></div>;
  return <form className="sheet-panel form-stack" onSubmit={async (e) => { e.preventDefault(); await addLog(activityId, Number(value)); finish(); }}><div className="sheet-head"><div><span className="eyebrow">项目记录</span><h2>完成了多少？</h2></div><button className="icon-button" type="button" onClick={onClose}><X /></button></div><label>项目<select value={activityId} onChange={(e) => setActivityId(e.target.value)}>{activities.filter(a => a.type !== "control").map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>数值<input className="large-field" value={value} onChange={(e) => setValue(e.target.value)} inputMode="numeric" /></label><button className="primary-button" type="submit">保存记录</button></form>;
}

function TodayView({ openQuick }: { openQuick: () => void }) {
  const { activities, logs, transactions, addLog, setView } = useLifeStore();
  const today = new Date().toISOString().slice(0,10);
  const todayLogs = logs.filter(l => l.createdAt.startsWith(today));
  const completed = activities.filter(a => todayLogs.some(l => l.activityId === a.id)).length;
  const todaySpend = transactions.filter(t => t.type === "expense" && t.occurredAt.startsWith(today)).reduce((s,t) => s+t.amount,0);
  const formatter = new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "long" });
  return <div className="page"><header className="hero"><div><span className="date">{formatter.format(new Date())}</span><h1>今天，稳稳向前。</h1><p>把重要的事做好一点，就已经很不错。</p></div><div className="score"><b>{completed}<span> / {activities.length}</span></b><small>今日已完成</small></div></header><div className="progress-line"><i style={{ width: `${activities.length ? completed/activities.length*100 : 0}%` }} /></div><section className="section"><div className="section-title"><div><span className="eyebrow">今日项目</span><h2>接下来做什么</h2></div><button className="text-button" onClick={() => setView("activities")}>管理项目 <ChevronRight /></button></div><div className="activity-list">{activities.map(activity => { const Icon = activityIcon(activity.icon); const ownLogs = todayLogs.filter(l => l.activityId === activity.id); const total = ownLogs.reduce((s,l) => s+(l.value ?? 1),0); const done = ownLogs.length>0; return <div className="activity-row" key={activity.id}><div className="activity-mark"><Icon /></div><div className="activity-main"><div><h3>{activity.name}</h3><p>{activity.type === "control" ? (done ? "今日状态已记录" : "今日状态尚未记录") : `${activity.targetPeriod === "weekly" ? "本周" : "今日"}目标 ${activity.normalTarget ?? 1} ${activity.unit}`}</p></div><div className="activity-value">{done ? <><b>{total || "已完成"}</b><span>{typeof total === "number" && total ? activity.unit : ""}</span></> : <span>待记录</span>}</div></div><button className={`row-action ${done ? "done" : ""}`} onClick={() => activity.type === "control" ? openQuick() : addLog(activity.id, activity.type === "duration" ? 15 : 1)} aria-label={`记录${activity.name}`}>{done ? <Check /> : <Plus />}</button></div>})}</div></section><section className="two-column"><button className="plain-card finance-summary" onClick={openQuick}><div><span className="eyebrow">今日支出</span><b>¥ {todaySpend.toFixed(2)}</b><small>{transactions.filter(t => t.occurredAt.startsWith(today)).length} 笔记录</small></div><CircleDollarSign /></button><button className="plain-card review-summary" onClick={() => setView("review")}><div><span className="eyebrow">每日复盘</span><b>为今天留一页</b><small>预计用时 2 分钟</small></div><ChevronRight /></button></section></div>;
}

function CalendarView() { const { logs, transactions, reviews } = useLifeStore(); const [selected,setSelected]=useState(new Date().getDate()); const nowDate=new Date(); const first=(new Date(nowDate.getFullYear(),nowDate.getMonth(),1).getDay()+6)%7; const days=new Date(nowDate.getFullYear(),nowDate.getMonth()+1,0).getDate(); return <div className="page"><PageHead eyebrow="生活轨迹" title={`${nowDate.getMonth()+1}月日历`} subtitle="完成、支出与复盘，都落在具体的一天里。"/><div className="calendar-wrap"><div className="week-row">{"一二三四五六日".split("").map(d=><span key={d}>周{d}</span>)}</div><div className="calendar-grid">{Array.from({length:first}).map((_,i)=><span key={`e${i}`}/>) }{Array.from({length:days},(_,i)=>i+1).map(day=>{const key=`${nowDate.getFullYear()}-${String(nowDate.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`; const count=logs.filter(l=>l.createdAt.startsWith(key)).length; const spent=transactions.filter(t=>t.occurredAt.startsWith(key)&&t.type==="expense").reduce((s,t)=>s+t.amount,0); const reviewed=reviews.some(r=>r.reviewDate===key); return <button className={selected===day?"selected":""} key={day} onClick={()=>setSelected(day)}><b>{day}</b><span>{count>0&&<i className="dot green"/>}{spent>0&&<i className="dot amber"/>}{reviewed&&<i className="dot blue"/>}</span></button>})}</div></div><div className="day-detail"><span className="eyebrow">{nowDate.getMonth()+1}月{selected}日</span><h2>当天概览</h2><div className="metric-row"><div><b>{logs.filter(l=>new Date(l.createdAt).getDate()===selected).length}</b><span>项目记录</span></div><div><b>¥{transactions.filter(t=>new Date(t.occurredAt).getDate()===selected&&t.type==="expense").reduce((s,t)=>s+t.amount,0).toFixed(0)}</b><span>当日支出</span></div><div><b>{reviews.some(r=>new Date(r.reviewDate).getDate()===selected)?"已完成":"—"}</b><span>每日复盘</span></div></div></div></div> }

function ActivitiesView() {
  const {activities, logs, addActivity, updateActivity, archiveActivity} = useLifeStore();
  const [editing, setEditing] = useState<Activity | null>(null);
  const [adding, setAdding] = useState(false);
  const [name, setName] = useState("");
  const [type, setType] = useState<Activity["type"]>("duration");
  const [unit, setUnit] = useState("分钟");
  const [target, setTarget] = useState("30");
  const [period, setPeriod] = useState<Activity["targetPeriod"]>("daily");
  const openEdit = (activity: Activity) => { setEditing(activity); setName(activity.name); setType(activity.type); setUnit(activity.unit); setTarget(String(activity.normalTarget ?? 1)); setPeriod(activity.targetPeriod); };
  const close = () => { setAdding(false); setEditing(null); setName(""); setType("duration"); setUnit("分钟"); setTarget("30"); setPeriod("daily"); };
  const save = async () => {
    const data = { name, type, unit, normalTarget: Number(target), targetPeriod: period };
    if (editing) await updateActivity(editing.id, data); else await addActivity(data);
    close();
  };
  return <div className="page"><PageHead eyebrow="长期项目" title="项目管理" subtitle="用清晰的目标替代短暂的热情。" action={<button className="primary-button small" onClick={()=>setAdding(true)}><Plus/> 新建项目</button>}/><div className="table-list"><div className="table-head"><span>项目</span><span>周期</span><span>累计</span><span>操作</span></div>{activities.map(a=><div className="table-row" key={a.id}><span><b>{a.name}</b><small>{activityTypeLabel(a.type)} · {a.unit}</small></span><span>{a.targetPeriod==="daily"?"每日":"每周"} {a.normalTarget??1} {a.unit}</span><span className="mono">{logs.filter(l=>l.activityId===a.id).reduce((s,l)=>s+(l.value??1),0)} {a.unit}</span><span className="row-tools"><button onClick={()=>openEdit(a)} aria-label={`编辑${a.name}`}><Pencil/></button><button onClick={()=>archiveActivity(a.id)} aria-label={`归档${a.name}`}><Archive/></button></span></div>)}</div>{(adding||editing)&&<div className="overlay"><form className="sheet-panel form-stack" onSubmit={async e=>{e.preventDefault();await save()}}><div className="sheet-head"><div><span className="eyebrow">{editing?"调整目标":"建立新习惯"}</span><h2>{editing?"编辑项目":"新建项目"}</h2></div><button type="button" className="icon-button" onClick={close}><X/></button></div><label>项目名称<input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="例如：阅读"/></label><label>目标类型<select value={type} onChange={e=>{const next=e.target.value as Activity["type"];setType(next);setUnit(next==="duration"?"分钟":next==="completion"?"项":"次")}}>{[["duration","时长型"],["count","次数型"],["completion","完成型"],["weekly","每周型"],["control","行为管理"]].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="form-grid"><label>目标值<input required min="1" type="number" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>单位<input required value={unit} onChange={e=>setUnit(e.target.value)}/></label></div><label>目标周期<select value={period} onChange={e=>setPeriod(e.target.value as Activity["targetPeriod"])}><option value="daily">每日</option><option value="weekly">每周</option></select></label><button className="primary-button">{editing?"保存修改":"创建项目"}</button></form></div>}</div>
}

const activityTypeLabel = (type: Activity["type"]) => ({ duration: "时长型", count: "次数型", completion: "完成型", weekly: "每周型", control: "行为管理" })[type];

function FinanceView({openQuick}:{openQuick:()=>void}) { const {transactions}=useLifeStore(); const month=new Date().toISOString().slice(0,7); const expense=transactions.filter(t=>t.type==="expense"&&t.occurredAt.startsWith(month)).reduce((s,t)=>s+t.amount,0); const income=transactions.filter(t=>t.type==="income"&&t.occurredAt.startsWith(month)).reduce((s,t)=>s+t.amount,0); return <div className="page"><PageHead eyebrow="简单记账" title="资金流动" subtitle="只记录事实，不制造焦虑。" action={<button className="primary-button small" onClick={openQuick}><Plus/> 记一笔</button>}/><div className="finance-hero"><div><span>本月支出</span><b>¥ {expense.toFixed(2)}</b><small>较上月 <em>— 12.4%</em></small></div><div className="finance-side"><span>本月收入 <b>¥ {income.toFixed(2)}</b></span><span>本月结余 <b>¥ {(income-expense).toFixed(2)}</b></span></div></div><section className="section"><div className="section-title"><div><span className="eyebrow">明细</span><h2>最近交易</h2></div></div><div className="transaction-list">{transactions.length===0?<Empty text="还没有交易，记录第一笔吧。"/>:transactions.slice(0,8).map(t=><div key={t.id}><span className="transaction-icon">{t.category.slice(0,1)}</span><span><b>{t.category}</b><small>{new Date(t.occurredAt).toLocaleDateString("zh-CN")} · {t.account}</small></span><strong className={t.type}> {t.type==="expense"?"−":"+"} ¥{t.amount.toFixed(2)}</strong></div>)}</div></section></div> }

function StatisticsView() {
  const {activities,logs,transactions}=useLifeStore();
  const expense=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);
  const completed=logs.filter(l=>l.status==="completed").length;
  const minutes=logs.filter(l=>activities.find(a=>a.id===l.activityId)?.type==="duration").reduce((s,l)=>s+(l.value??0),0);
  const days=Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));return date});
  const totals=days.map(date=>logs.filter(l=>l.createdAt.startsWith(date.toISOString().slice(0,10))&&activities.find(a=>a.id===l.activityId)?.type==="duration").reduce((sum,l)=>sum+(l.value??0),0));
  const max=Math.max(...totals,1);
  return <div className="page"><PageHead eyebrow="趋势，而非连续天数" title="你的长期变化" subtitle="看见总量、完成率和真正的趋势。"/><div className="metric-row large"><div><span>完成记录</span><b>{completed}</b><small>全部本地记录</small></div><div><span>投入时长</span><b>{minutes}<i> 分钟</i></b><small>累计专注</small></div><div><span>总支出</span><b>¥{expense.toFixed(0)}</b><small>当前数据</small></div></div><div className="chart-card"><div className="section-title"><div><span className="eyebrow">近 7 日</span><h2>每日投入趋势</h2></div></div><div className="bar-chart">{totals.map((total,i)=><div key={days[i].toISOString()} title={`${total} 分钟`}><span style={{height:`${Math.max(total/max*100,total?8:2)}%`}}/><small>{new Intl.DateTimeFormat("zh-CN",{weekday:"short"}).format(days[i]).replace("周","")}</small></div>)}</div></div><div className="activity-breakdown"><span className="eyebrow">项目完成概览</span>{activities.map(a=>{const value=logs.filter(l=>l.activityId===a.id).reduce((s,l)=>s+(l.value??1),0);const target=Math.max(a.normalTarget??1,1);const percent=Math.min(100,Math.round(value/target*100));return <div key={a.id}><span>{a.name}</span><i><b style={{width:`${percent}%`}}/></i><strong>{percent}%</strong></div>})}</div></div>
}

function ReviewView() { const {reviews,saveReview}=useLifeStore(); const current=reviews.find(r=>r.reviewDate===new Date().toISOString().slice(0,10)); const [energy,setEnergy]=useState(current?.energy??7); const [mood,setMood]=useState(current?.mood??7); const [best,setBest]=useState(current?.bestThing??""); const [priority,setPriority]=useState(current?.tomorrowPriority??""); const [saved,setSaved]=useState(false); return <div className="page narrow"><PageHead eyebrow="每日两分钟" title="把今天轻轻收好" subtitle="不评判，只是看清发生了什么。"/><form className="review-form" onSubmit={async e=>{e.preventDefault();await saveReview({energy,mood,bestThing:best,tomorrowPriority:priority});setSaved(true)}}><RangeField label="今天的精力" value={energy} onChange={setEnergy}/><RangeField label="今天的心情" value={mood} onChange={setMood}/><label><span>今天做得最好的一件事</span><textarea value={best} onChange={e=>setBest(e.target.value)} placeholder="哪怕是一件很小的事……"/></label><label><span>明天最重要的一件事</span><input value={priority} onChange={e=>setPriority(e.target.value)} placeholder="只写一件"/></label><button className="primary-button" type="submit">{saved?<><Check/> 已保存今天</>:"保存今日复盘"}</button></form></div> }

function SettingsView() {
  const {dark,toggleDark,syncState,activities,logs,transactions,reviews}=useLifeStore();
  const download=(content:string,type:string,name:string)=>{const blob=new Blob([content],{type});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
  const exportJson=()=>download(JSON.stringify({exportedAt:new Date().toISOString(),activities,logs,transactions,reviews},null,2),"application/json","lifetrace-export.json");
  const csv=(rows:Record<string,unknown>[])=>{if(!rows.length)return "";const headers=Object.keys(rows[0]);const cell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;return `\uFEFF${headers.map(cell).join(",")}\n${rows.map(row=>headers.map(key=>cell(row[key])).join(",")).join("\n")}`};
  const exportCsv=()=>{download(csv(logs.map(log=>({...log,metadata:JSON.stringify(log.metadata??{})}))),"text/csv;charset=utf-8","lifetrace-activity-logs.csv");download(csv(transactions),"text/csv;charset=utf-8","lifetrace-transactions.csv");download(csv(reviews),"text/csv;charset=utf-8","lifetrace-daily-reviews.csv")};
  return <div className="page narrow"><PageHead eyebrow="我的 LifeTrace" title="设置" subtitle="掌控自己的数据与使用方式。"/><div className="settings-list"><button onClick={toggleDark}><span><Moon/><b>外观模式</b></span><em>{dark?"深色":"浅色"} <ChevronRight/></em></button><button><span><Cloud/><b>数据同步</b></span><em>{syncState==="synced"?"已同步":syncState==="syncing"?"正在同步":"离线"} <ChevronRight/></em></button><button onClick={exportJson}><span><Download/><b>导出完整备份</b></span><em>JSON <ChevronRight/></em></button><button onClick={exportCsv}><span><BookOpen/><b>导出表格数据</b></span><em>3 个 CSV <ChevronRight/></em></button><button><span><UserRound/><b>本地账户</b></span><em>个人模式 <ChevronRight/></em></button></div><div className="privacy-note"><Shield/><div><b>你的数据属于你</b><p>记录会优先保存在这台设备中。连接云端后，将通过你的私有账户安全同步。</p></div></div></div>
}

function TimerBar() {
  const {timer,activities,startTimer,pauseTimer,finishTimer}=useLifeStore();
  const [tick,setTick]=useState(Date.now());
  useEffect(()=>{if(!timer?.startedAt)return;const id=window.setInterval(()=>setTick(Date.now()),1000);return()=>window.clearInterval(id)},[timer?.startedAt]);
  if(!timer)return null;
  const seconds=timer.accumulatedSeconds+(timer.startedAt?Math.floor((tick-timer.startedAt)/1000):0);
  const label=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  const activity=activities.find(item=>item.id===timer.activityId);
  return <div className="timer-bar"><div><span className="timer-pulse"/><span><small>正在记录</small><b>{activity?.name??"专注计时"}</b></span></div><strong>{label}</strong><div className="timer-actions"><button onClick={()=>timer.startedAt?pauseTimer():startTimer(timer.activityId)} aria-label={timer.startedAt?"暂停计时":"继续计时"}>{timer.startedAt?<Pause/>:<Play/>}</button><button className="finish" onClick={finishTimer} aria-label="完成计时"><Square/></button></div></div>
}

function PageHead({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:React.ReactNode}) { return <header className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</header> }
function Empty({text}:{text:string}) { return <div className="empty"><span>—</span><p>{text}</p></div> }
function RangeField({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}) { return <label className="range-field"><span>{label}<b>{value}<small>/10</small></b></span><input type="range" min="1" max="10" value={value} onChange={e=>onChange(Number(e.target.value))}/><div><span>低</span><span>充沛</span></div></label> }

export default function AppShell() {
  const {ready,view,setView,dark,toggleDark,syncState,initialize}=useLifeStore(); const [quick,setQuick]=useState(false); const [mobileMenu,setMobileMenu]=useState(false);
  useEffect(()=>{initialize();if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>undefined);},[initialize]); useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);
  if(!ready) return <div className="loading"><span className="brand-symbol">L</span><p>正在整理你的生活轨迹…</p></div>;
  const render=()=>{switch(view){case"calendar":return <CalendarView/>;case"activities":return <ActivitiesView/>;case"finance":return <FinanceView openQuick={()=>setQuick(true)}/>;case"statistics":return <StatisticsView/>;case"review":return <ReviewView/>;case"settings":return <SettingsView/>;default:return <TodayView openQuick={()=>setQuick(true)}/>}};
  return <main className="app-shell"><aside className={mobileMenu?"open":""}><div className="brand"><span className="brand-symbol">L</span><div><b>LifeTrace</b><small>日常 · 长期主义</small></div></div><nav>{nav.map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMobileMenu(false)}}><Icon/><span>{label}</span></button>)}</nav><div className="aside-foot"><button onClick={toggleDark}>{dark?<Sun/>:<Moon/>}<span>{dark?"浅色模式":"深色模式"}</span></button><div className="sync"><i className={syncState}/>{syncState==="synced"?<Cloud/>:<CloudOff/>}<span>{syncState==="synced"?"已同步到此设备":syncState==="syncing"?"正在同步":"离线可用"}</span></div></div></aside><div className="workspace"><div className="mobile-top"><button className="icon-button" onClick={()=>setMobileMenu(!mobileMenu)}><Menu/></button><div className="brand"><span className="brand-symbol">L</span><b>LifeTrace</b></div><div className="sync-mini"><i className={syncState}/></div></div>{render()}</div><TimerBar/><button className="floating-add" onClick={()=>setQuick(true)}><Plus/><span>记录</span></button><div className="mobile-nav">{nav.slice(0,2).map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span>{label}</span></button>)}<button className="record" onClick={()=>setQuick(true)}><Plus/><span>记录</span></button>{[{id:"statistics" as ViewId,label:"统计",icon:BarChart3},{id:"settings" as ViewId,label:"我的",icon:UserRound}].map(({id,label,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon/><span>{label}</span></button>)}</div>{quick&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setQuick(false)}}><QuickSheet onClose={()=>setQuick(false)}/></div>}</main>;
}
