import { useMemo, useState, type FormEvent } from "react";
import { BookOpen, Check, FileText, Plus, RefreshCw } from "lucide-react";
import { Badge, Button, Card, ChartContainer, EmptyState, Input, List, ListItem, Progress, SearchField, Select, Switch, Textarea } from "../design-system/ui";
import { isoDate, newId, reviewMetrics, searchState, type LifeTraceState } from "../model";
import type { PlatformAdapter } from "../platform";
import { PageHeader, Section, type SetLifeTraceState } from "./shared";

export function ReadingPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const [selectedId, setSelectedId] = useState<string | null>(state.reading[0]?.id ?? null);
  const [title, setTitle] = useState("");
  const selected = state.reading.find((item) => item.id === selectedId) ?? state.reading[0];
  const add = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; const item = { id: newId("reading"), title: title.trim(), source: "Manual", progress: 0, completed: false, highlights: [], note: "" }; setState((current) => ({ ...current, reading: [item, ...current.reading] })); setSelectedId(item.id); setTitle(""); };
  return <><PageHeader title="Reading / English" detail="正文、高亮、快捷笔记与完成反馈保持内容优先。" /><form className="lt-row" onSubmit={add}><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="添加阅读材料标题…" style={{ flex: 1 }} /><Button type="submit"><Plus size={17} />添加</Button></form><div className="lt-grid-2 lt-section" style={{ gridTemplateColumns: "minmax(220px, .7fr) minmax(0, 1.5fr)" }}><List>{state.reading.length ? state.reading.map((item) => <ListItem key={item.id} className={item.id === selected?.id ? "is-selected" : ""}><button className="lt-button ghost" style={{ width: "100%", justifyContent: "flex-start", paddingInline: 0 }} onClick={() => setSelectedId(item.id)}><BookOpen size={17} /><span style={{ textAlign: "left", flex: 1 }}>{item.title}<span className="lt-caption" style={{ display: "block" }}>{item.completed ? "已读" : `${item.progress}%`}</span></span></button></ListItem>) : <EmptyState title="阅读列表为空" detail="添加一篇文章开始阅读闭环。" />}</List>{selected ? <Card><article className="lt-reader"><div className="lt-caption">{selected.source}</div><h2>{selected.title}</h2><p className="lt-muted">阅读状态与笔记通过 English Learning Record 同步到 LifeTrace Cloud。</p><Progress value={selected.progress} label="阅读进度" /><input style={{ width: "100%", margin: "20px 0" }} aria-label="阅读进度" type="range" min="0" max="100" value={selected.progress} onChange={(event) => setState((current) => ({ ...current, reading: current.reading.map((item) => item.id === selected.id ? { ...item, progress: Number(event.target.value) } : item) }))} /><Textarea value={selected.note} onChange={(event) => setState((current) => ({ ...current, reading: current.reading.map((item) => item.id === selected.id ? { ...item, note: event.target.value } : item) }))} placeholder="快捷笔记（不重复展示原句）" /><Button style={{ marginTop: 12 }} onClick={() => setState((current) => ({ ...current, reading: current.reading.map((item) => item.id === selected.id ? { ...item, completed: true, progress: 100 } : item) }))}><Check size={17} />标记读完</Button></article></Card> : <EmptyState title="选择一篇内容" detail="正文区域将在选择后打开。" />}</div></>;
}

export function NotesPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const [selectedId, setSelectedId] = useState<string | null>(state.notes[0]?.id ?? null);
  const selected = state.notes.find((note) => note.id === selectedId) ?? state.notes[0];
  const create = () => { const note = { id: newId("note"), title: "未命名笔记", content: "", updatedAt: new Date().toISOString(), pinned: false }; setState((current) => ({ ...current, notes: [note, ...current.notes] })); setSelectedId(note.id); };
  const update = (patch: Partial<{ title: string; content: string; pinned: boolean }>) => selected && setState((current) => ({ ...current, notes: current.notes.map((note) => note.id === selected.id ? { ...note, ...patch, updatedAt: new Date().toISOString() } : note) }));
  return <><PageHeader title="Notes" detail="桌面采用 List + Editor，避免卡片瀑布流。" action={<Button onClick={create}><Plus size={17} />New note</Button>} /><div className="lt-notes-layout"><List>{state.notes.length ? state.notes.map((note) => <ListItem key={note.id}><button className="lt-button ghost" style={{ width: "100%", justifyContent: "flex-start", padding: 0 }} onClick={() => setSelectedId(note.id)}><FileText size={17} /><span style={{ textAlign: "left", flex: 1 }}>{note.title || "未命名笔记"}<span className="lt-caption" style={{ display: "block" }}>{new Date(note.updatedAt).toLocaleString("zh-CN")}</span></span></button></ListItem>) : <EmptyState title="没有笔记" detail="新建一条笔记开始记录。" />}</List>{selected ? <Card><Input value={selected.title} onChange={(event) => update({ title: event.target.value })} aria-label="笔记标题" style={{ width: "100%", background: "transparent", fontSize: 24, fontWeight: 600, paddingInline: 0 }} /><textarea className="lt-note-editor" aria-label="笔记内容" value={selected.content} onChange={(event) => update({ content: event.target.value })} placeholder="开始写作…" /></Card> : <EmptyState title="选择或新建笔记" detail="编辑器会在这里打开。" />}</div></>;
}

export function ReviewPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const metrics = reviewMetrics(state);
  const existing = state.reviews.find((item) => item.date === isoDate()) ?? { date: isoDate(), bestThing: "", problem: "", tomorrowPriority: "" };
  const save = (field: "bestThing" | "problem" | "tomorrowPriority", value: string) => setState((current) => ({ ...current, reviews: [...current.reviews.filter((item) => item.date !== isoDate()), { ...existing, [field]: value }] }));
  return <><PageHeader title="Review" detail="突出已完成事项、关键趋势和下一步。" /><div className="lt-grid-2"><ChartContainer title="Task completion"><div style={{ padding: "18px 0" }}><strong style={{ fontSize: 42 }}>{Math.round(metrics.taskCompletion * 100)}%</strong><Progress label="任务完成率" value={metrics.taskCompletion * 100} /></div></ChartContainer><ChartContainer title="Habit completion"><div style={{ padding: "18px 0" }}><strong style={{ fontSize: 42 }}>{Math.round(metrics.habitCompletion * 100)}%</strong><Progress label="习惯完成率" value={metrics.habitCompletion * 100} /></div></ChartContainer></div><Section title="Daily reflection"><Card><div className="lt-form-grid"><label>今天最好的一件事<Textarea value={existing.bestThing} onChange={(event) => save("bestThing", event.target.value)} /></label><label>阻碍 / 问题<Textarea value={existing.problem} onChange={(event) => save("problem", event.target.value)} /></label><label>明天最重要的事<Textarea value={existing.tomorrowPriority} onChange={(event) => save("tomorrowPriority", event.target.value)} /></label></div></Card></Section></>;
}

export function SearchPage({ state, navigate }: { state: LifeTraceState; navigate: (path: string) => void }) {
  const [query, setQuery] = useState("");
  const results = useMemo(() => searchState(state, query), [state, query]);
  return <><PageHeader title="Search" detail="跨任务、笔记、阅读和财务记录检索个人工作区。" /><SearchField autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索 LifeTrace…" />{query && <Section title={`Results · ${results.length}`}>{results.length ? <List>{results.map((item) => <ListItem key={`${item.type}-${item.id}`}><Badge>{item.type}</Badge><button className="lt-button ghost" style={{ flex: 1, justifyContent: "flex-start" }} onClick={() => navigate(item.path)}>{item.title}</button></ListItem>)}</List> : <EmptyState title="没有匹配结果" detail="尝试更短或更具体的关键词。" />}</Section>}</>;
}

export function SettingsPage({ state, setState, platform, onLogout, onReload }: { state: LifeTraceState; setState: SetLifeTraceState; platform: PlatformAdapter; onLogout: () => Promise<void>; onReload: () => Promise<void> }) {
  const [status, setStatus] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  const refresh = async () => { if (!platform.getNativeStatus) return; setBusy(true); try { setStatus(await platform.getNativeStatus()); } finally { setBusy(false); } };
  return <><PageHeader title="Settings" detail="外观、同步、账户和桌面原生能力集中管理。" /><div className="lt-grid-2"><Card><h3 style={{ marginTop: 0 }}>Appearance</h3><div className="lt-row-between" style={{ marginBottom: 16 }}><span>Theme</span><Select value={state.settings.theme} onChange={(event) => setState((current) => ({ ...current, settings: { ...current.settings, theme: event.target.value as "system" | "light" | "dark" } }))}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></Select></div><div className="lt-row-between"><span>Reduced motion</span><Switch label="减少动态效果" checked={state.settings.reducedMotion} onChange={(checked) => setState((current) => ({ ...current, settings: { ...current.settings, reducedMotion: checked } }))} /></div></Card><Card><div className="lt-row-between"><div><h3 style={{ margin: 0 }}>Platform</h3><p className="lt-muted">{platform.label}</p></div><Badge tone={platform.kind === "desktop" ? "accent" : "neutral"}>{platform.kind}</Badge></div>{platform.kind === "desktop" ? <><Button className="secondary" onClick={refresh} disabled={busy}><RefreshCw size={17} />{busy ? "Checking…" : "Native status"}</Button>{platform.syncNow ? <Button style={{ marginLeft: 8 }} onClick={() => void platform.syncNow?.()}>Sync now</Button> : null}</> : <div className="lt-row"><Button className="secondary" onClick={() => void onReload()}><RefreshCw size={17} />Sync now</Button><Button className="secondary" onClick={() => void onLogout()}>Log out</Button></div>}</Card></div>{status ? <Section title="Native diagnostics"><Card><pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere", margin: 0, fontSize: 12 }}>{JSON.stringify(status, null, 2)}</pre></Card></Section> : null}</>;
}
