import { useState, type FormEvent } from "react";
import { Plus } from "lucide-react";
import { Badge, Button, Card, Checkbox, EmptyState, Input, List, ListItem, Progress, SegmentedControl, Select, StatCard } from "../design-system/ui";
import { isoDate, newId, reviewMetrics, type LifeTraceState } from "../model";
import { PageHeader, Section, type SetLifeTraceState } from "./shared";

export function TodayPage({ state, setState, openQuickCapture }: { state: LifeTraceState; setState: SetLifeTraceState; openQuickCapture: () => void }) {
  const today = isoDate();
  const tasks = state.tasks.filter((task) => task.dueDate === today);
  const metrics = reviewMetrics(state, today);
  const priority = tasks.find((task) => !task.completed && task.priority === "high") ?? tasks.find((task) => !task.completed);
  const workouts = state.workouts.filter((workout) => workout.date === today);
  const toggleTask = (id: string) => setState((current) => ({ ...current, tasks: current.tasks.map((task) => task.id === id ? { ...task, completed: !task.completed } : task) }));
  const toggleHabit = (id: string) => setState((current) => ({ ...current, habits: current.habits.map((habit) => habit.id !== id ? habit : { ...habit, completedDates: habit.completedDates.includes(today) ? habit.completedDates.filter((date) => date !== today) : [...habit.completedDates, today], streak: habit.completedDates.includes(today) ? Math.max(0, habit.streak - 1) : habit.streak + 1 }) }));
  return <>
    <PageHeader title="Today" detail={`${new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "long" }).format(new Date())} · 只保留今天真正需要行动的信息。`} action={<Button onClick={openQuickCapture}><Plus size={17} /> Quick Capture</Button>} />
    <div className="lt-metrics"><StatCard label="今日任务" value={`${metrics.completedTasks}/${metrics.totalTasks}`} detail="完成 / 计划" /><StatCard label="习惯" value={`${metrics.completedHabits}/${metrics.totalHabits}`} detail="今日打卡" /><StatCard label="训练" value={workouts.reduce((sum, item) => sum + item.durationMinutes, 0)} detail="分钟" /></div>
    <div className="lt-grid-2 lt-section"><Card><div className="lt-caption">TODAY FOCUS</div><h2 style={{ margin: "10px 0 8px" }}>{priority?.title ?? "为今天设定一个重点"}</h2><p className="lt-muted" style={{ margin: 0 }}>{priority ? `${priority.project || "Inbox"} · ${priority.priority === "high" ? "高优先级" : "下一步行动"}` : "用 Quick Capture 添加今天最重要的行动。"}</p></Card><Card><div className="lt-caption">NEXT SIGNAL</div><h2 style={{ margin: "10px 0 8px" }}>{state.reading.find((item) => !item.completed)?.title ?? "保持输入与输出平衡"}</h2><p className="lt-muted" style={{ margin: 0 }}>{state.reading.length ? "继续最近的阅读记录，完成后留下简短笔记。" : "保持输入、行动与复盘之间的节奏。"}</p></Card></div>
    <Section title="Tasks">{tasks.length ? <List>{tasks.map((task) => <ListItem key={task.id}><Checkbox checked={task.completed} onChange={() => toggleTask(task.id)} aria-label={`完成 ${task.title}`} /><div style={{ flex: 1 }}><div style={{ textDecoration: task.completed ? "line-through" : undefined }}>{task.title}</div><span className="lt-caption">{task.project || "Inbox"}</span></div>{task.priority === "high" ? <Badge tone="danger">High</Badge> : null}</ListItem>)}</List> : <EmptyState title="今天还没有任务" detail="只把今天真正要推进的事项放进来。" action={<Button className="secondary" onClick={openQuickCapture}>添加任务</Button>} />}</Section>
    <Section title="Habits">{state.habits.length ? <List>{state.habits.map((habit) => { const done = habit.completedDates.includes(today); return <ListItem key={habit.id}><Checkbox checked={done} onChange={() => toggleHabit(habit.id)} aria-label={`打卡 ${habit.name}`} /><div style={{ flex: 1 }}>{habit.name}<div className="lt-caption">连续 {habit.streak} 天</div></div><Badge tone={done ? "success" : "neutral"}>{done ? "已完成" : "待打卡"}</Badge></ListItem>; })}</List> : <EmptyState title="建立第一个习惯" detail="习惯趋势留在 Habits，Today 只负责今天。" />}</Section>
  </>;
}

export function PlanPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const [scope, setScope] = useState<"inbox" | "today" | "upcoming" | "completed">("today");
  const [title, setTitle] = useState("");
  const today = isoDate();
  const visible = state.tasks.filter((task) => scope === "inbox" ? !task.completed && !task.project : scope === "today" ? !task.completed && task.dueDate === today : scope === "upcoming" ? !task.completed && task.dueDate > today : task.completed);
  const addTask = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; setState((current) => ({ ...current, tasks: [{ id: newId("task"), title: title.trim(), dueDate: today, project: "", priority: "normal", completed: false }, ...current.tasks] })); setTitle(""); };
  return <><PageHeader title="Plan" detail="用清晰列表管理 Inbox、Today、Upcoming 与 Completed。" /><div className="lt-row-between" style={{ marginBottom: 16 }}><SegmentedControl label="任务范围" value={scope} onChange={setScope} options={[{ value: "inbox", label: "Inbox" }, { value: "today", label: "Today" }, { value: "upcoming", label: "Upcoming" }, { value: "completed", label: "Completed" }]} /></div><form className="lt-row" onSubmit={addTask} style={{ marginBottom: 14 }}><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="新增任务…" style={{ flex: 1 }} /><Button type="submit"><Plus size={17} />添加</Button></form>{visible.length ? <List>{visible.map((task) => <ListItem key={task.id}><Checkbox checked={task.completed} onChange={() => setState((current) => ({ ...current, tasks: current.tasks.map((item) => item.id === task.id ? { ...item, completed: !item.completed } : item) }))} aria-label={`完成 ${task.title}`} /><div style={{ flex: 1 }}><strong style={{ fontWeight: 500 }}>{task.title}</strong><div className="lt-caption">{task.dueDate} · {task.project || "Inbox"}</div></div><Select aria-label="优先级" value={task.priority} onChange={(event) => setState((current) => ({ ...current, tasks: current.tasks.map((item) => item.id === task.id ? { ...item, priority: event.target.value as "low" | "normal" | "high" } : item) }))}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></Select></ListItem>)}</List> : <EmptyState title="这里已经清空" detail="没有待处理项目。" />}</>;
}

export function CalendarPage({ state }: { state: LifeTraceState }) {
  const now = new Date(); const year = now.getFullYear(); const month = now.getMonth(); const days = new Date(year, month + 1, 0).getDate();
  return <><PageHeader title="Calendar" detail="桌面月视图，窄窗口自动转为可扫描布局。" /><div className="lt-calendar-grid">{Array.from({ length: days }, (_, index) => index + 1).map((day) => { const date = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; const items = state.tasks.filter((task) => task.dueDate === date); return <div className="lt-day-cell" key={day}><strong>{day}</strong>{items.slice(0, 3).map((task) => <small key={task.id}>{task.completed ? "✓ " : ""}{task.title}</small>)}</div>; })}</div></>;
}

export function HabitsPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const [name, setName] = useState(""); const today = isoDate();
  const add = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setState((current) => ({ ...current, habits: [...current.habits, { id: newId("habit"), name: name.trim(), targetDays: 7, streak: 0, completedDates: [] }] })); setName(""); };
  return <><PageHeader title="Habits" detail="当天打卡优先，趋势用于反馈。" /><form className="lt-row" onSubmit={add}><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="添加习惯…" style={{ flex: 1 }} /><Button type="submit"><Plus size={17} />添加</Button></form><Section title="Today check-in">{state.habits.length ? <List>{state.habits.map((habit) => { const done = habit.completedDates.includes(today); const recent = Array.from({ length: 7 }, (_, i) => { const date = new Date(); date.setDate(date.getDate() - i); return habit.completedDates.includes(isoDate(date)); }).filter(Boolean).length; return <ListItem key={habit.id}><Checkbox checked={done} aria-label={`打卡 ${habit.name}`} onChange={() => setState((current) => ({ ...current, habits: current.habits.map((item) => item.id === habit.id ? { ...item, completedDates: done ? item.completedDates.filter((date) => date !== today) : [...item.completedDates, today], streak: done ? Math.max(0, item.streak - 1) : item.streak + 1 } : item) }))} /><div style={{ flex: 1 }}><div className="lt-row-between"><strong style={{ fontWeight: 500 }}>{habit.name}</strong><span className="lt-caption">7 日 {recent}/7</span></div><Progress label={`${habit.name} 七日完成率`} value={(recent / 7) * 100} /></div><Badge tone={habit.streak >= 3 ? "success" : "neutral"}>{habit.streak} day streak</Badge></ListItem>; })}</List> : <EmptyState title="没有习惯" detail="从一个可每天执行的小动作开始。" />}</Section></>;
}

export function FitnessPage({ state, setState }: { state: LifeTraceState; setState: SetLifeTraceState }) {
  const [title, setTitle] = useState(""); const [minutes, setMinutes] = useState("45");
  const add = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; setState((current) => ({ ...current, workouts: [{ id: newId("workout"), date: isoDate(), title: title.trim(), durationMinutes: Number(minutes) || 0, volume: 0 }, ...current.workouts] })); setTitle(""); };
  const week = state.workouts.slice(0, 7);
  return <><PageHeader title="Fitness / Health" detail="本周训练、训练量和身体趋势组成克制的分析工作区。" /><div className="lt-metrics"><StatCard label="本周训练" value={week.length} detail="sessions" /><StatCard label="训练时长" value={week.reduce((sum, item) => sum + item.durationMinutes, 0)} detail="minutes" /><StatCard label="训练量" value={week.reduce((sum, item) => sum + item.volume, 0).toLocaleString()} detail="volume" /></div><Section title="Record workout"><form className="lt-form-grid two" onSubmit={add}><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="训练名称" /><Input aria-label="训练分钟" value={minutes} onChange={(event) => setMinutes(event.target.value)} inputMode="numeric" /><Button type="submit"><Plus size={17} />记录训练</Button></form></Section><Section title="Recent workouts">{state.workouts.length ? <List>{state.workouts.map((workout) => <ListItem key={workout.id}><div style={{ flex: 1 }}><strong>{workout.title}</strong><div className="lt-caption">{workout.date}</div></div><Badge>{workout.durationMinutes} min</Badge></ListItem>)}</List> : <EmptyState title="还没有训练记录" detail="记录一次训练后，这里会展示最近的训练趋势。" />}</Section></>;
}
